export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';


export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';


export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';


export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';


export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';

